name: Connector - Build & Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Run Tests
        run: npm test
