name: Connector - Build & Test

permissions:
  checks: write
  pull-requests: write

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.7'

      - name: Install node dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results.xml
