name: Connector - Build & Test

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - 'v*'
    branches:
      - 'master'
      - 'release/connector/*'
      - 'support/connector/*'

permissions:
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.7'

      - name: Download Python Deps
        run: pip install -r resources/scripts/requirements.txt
        working-directory: ./rticonnextdds-connector

      - name: Download libs
        run: python3 resources/scripts/download_latest_libs.py --storage-url ${{ secrets.COMMUNITY_S3_URL }} --storage-path ${{ secrets.COMMUNITY_S3_PATH }} -o .
        working-directory: ./rticonnextdds-connector

      - name: Install node dependencies
        run: npm install

      - name: Run Tests
        run: npm run test-json

      - uses: dorny/test-reporter@v1
        with:
          name: Tests results
          path: 'test-results.json'
          reporter: mocha-json

      - name: Publish npm package
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
