name: Connector - Build & Test

permissions:
  checks: write

on:
  push:
    paths:
      - 'docs/**'
      - 'rticonnextdds-connector.js'
      - '.github/workflows/build_doc.yml'

  pull_request:
    paths:
      - 'docs/**'
      - 'rticonnextdds-connector.js'
      - '.github/workflows/build_doc.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.7'

      - name: Install node dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'rticonnextdds-connector.js'
