name: Connector - Build & Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.7'

      - name: Install node dependencies
        run: npm install

      - name: Run Tests
        run: npm run test-json

      - uses: dorny/test-reporter@v1
        with:
          name: Tests results
          path: 'test-results.json'
          reporter: mocha-json
