name: Connector - Build Doc

on:
  push:
    paths:
      - 'docs/**'
      - 'rticonnextdds-connector.js'
      - '.github/workflows/build_doc.yml'

  pull_request:
    paths:
      - 'docs/**'
      - 'rticonnextdds-connector.js'
      - '.github/workflows/build_doc.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.7'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8' 

      - name: Install jsdoc
        run: npm install -g jsdoc

      - name: Install Python Dependencies
        run: pip install -r docs/requirements.txt

      - name: Build HTML
        run: make html -C docs

      - name: Archive HTML documentation
        uses: actions/upload-artifact@v3
        with:
          name: HTML doc
          path: docs/_build/html
